language: julia
os:
  - linux
  - osx
julia:
  - release
#  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("CAIRS"); Pkg.test("CAIRS"; coverage=true)'
  - grep -v Rscript  ./example/Example_highlevel_interface.jl > example_without_R.jl
  - julia --code-coverage ./example_without_R.jl
after_success:
  - julia -e 'cd(Pkg.dir("CAIRS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
