language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("CAIRS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'