branches:
  only:
    - master
language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("CAIRS"))`); Pkg.pin("CAIRS"); Pkg.resolve()'
  - julia -e 'using CAIRS; @assert isdefined(:CAIRS); @assert typeof(CAIRS) === Module'
  - julia --code-coverage ./test/tests.jl
  - grep -v Rscript  ./example/Example_highlevel_interface.jl > example_without_R.jl
  - julia --code-coverage ./example_without_R.jl
  - julia -e 'cd(Pkg.dir("MyPackage")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
